//! Platform-specific default paths for config files and keys, plus config
//! template rendering and private-key permission hardening.
//!
//! Two scopes are supported:
//! - **System-level** ([`Scope::System`]): machine-wide, used when running as
//!   a service. Requires admin/root to write.
//!   - Linux: `/etc/optical/`
//!   - Windows: `%PROGRAMDATA%\optical\`
//! - **User-level** ([`Scope::User`], default): per-user, used for foreground
//!   / dev runs.
//!   - Linux: `$XDG_CONFIG_HOME/optical/` or `~/.config/optical/`
//!   - Windows: `%APPDATA%\optical\`

use std::path::{Path, PathBuf};

/// The deployment scope determining the default base directory.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Scope {
    /// Machine-wide directory (requires admin/root to write).
    System,
    /// Per-user directory (default).
    User,
}

impl std::fmt::Display for Scope {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Scope::System => write!(f, "system"),
            Scope::User => write!(f, "user"),
        }
    }
}

/// The embedded config template (from `config.example.yml` at build time).
pub const CONFIG_TEMPLATE: &str = include_str!("../config.example.yml");

/// The all-zero placeholder PSK embedded in the template (includes `hex:` prefix).
const PSK_PLACEHOLDER: &str =
    "hex:0000000000000000000000000000000000000000000000000000000000000000";

// ── Directory resolution ─────────────────────────────────────────────────────

/// Compute the base directory for the given scope.
///
/// Returns `None` for [`Scope::User`] when the user home / app-data directory
/// cannot be determined.
pub fn base_dir(scope: Scope) -> Option<PathBuf> {
    match scope {
        Scope::System => Some(system_dir()),
        Scope::User => user_dir(),
    }
}

/// System-level directory for optical config and keys.
pub fn system_dir() -> PathBuf {
    #[cfg(target_os = "windows")]
    {
        let base = std::env::var("PROGRAMDATA")
            .map(PathBuf::from)
            .unwrap_or_else(|_| PathBuf::from(r"C:\ProgramData"));
        base.join("optical")
    }
    #[cfg(not(target_os = "windows"))]
    {
        PathBuf::from("/etc/optical")
    }
}

/// User-level directory for optical config and keys.
///
/// Returns `None` if the home directory cannot be determined.
pub fn user_dir() -> Option<PathBuf> {
    #[cfg(target_os = "windows")]
    {
        std::env::var("APPDATA")
            .ok()
            .filter(|s| !s.is_empty())
            .map(PathBuf::from)
            .map(|p| p.join("optical"))
    }
    #[cfg(not(target_os = "windows"))]
    {
        if let Ok(xdg) = std::env::var("XDG_CONFIG_HOME") {
            if !xdg.is_empty() && xdg != "/" {
                return Some(PathBuf::from(xdg).join("optical"));
            }
        }
        std::env::var("HOME")
            .ok()
            .filter(|h| !h.is_empty())
            .map(|h| PathBuf::from(h).join(".config").join("optical"))
    }
}

/// Default config file path (`config.yml`) for a scope.
#[allow(dead_code)]
pub fn default_config_path(scope: Scope) -> Option<PathBuf> {
    base_dir(scope).map(|d| d.join("config.yml"))
}

/// Default private key path (`keys/node.key`) for a scope.
pub fn default_private_key_path(scope: Scope) -> Option<PathBuf> {
    base_dir(scope).map(|d| d.join("keys").join("node.key"))
}

/// Default public key path (`keys/node.pub`) for a scope.
pub fn default_public_key_path(scope: Scope) -> Option<PathBuf> {
    base_dir(scope).map(|d| d.join("keys").join("node.pub"))
}

// ── Config template rendering ────────────────────────────────────────────────

/// Normalize a path for embedding in a YAML double-quoted string.
///
/// Backslashes are converted to forward slashes so the path is safe inside
/// YAML double-quoted scalars (where `\` is an escape character). Both Rust's
/// `Path` and the OS accept forward slashes on Windows.
fn yaml_path(p: &Path) -> String {
    p.to_string_lossy().replace('\\', "/")
}

/// Render the config template with the given PSK, key paths, and log directory.
///
/// `psk_hex` must be the full `"hex:<64 hex chars>"` string.
/// `log_dir_path` is the directory for daily-rotating log files (typically a
/// sibling of the keys directory, e.g. `<base>/logs`).
/// A generation notice is prepended reminding the user to edit the file.
pub fn render_config(
    psk_hex: &str,
    private_key_path: &Path,
    public_key_path: &Path,
    log_dir_path: &Path,
) -> String {
    let priv_str = yaml_path(private_key_path);
    let pub_str = yaml_path(public_key_path);
    let log_str = yaml_path(log_dir_path);

    let header = "# ── Generated by `optical init` — EDIT BEFORE USE ────────────────────────\n\
                  # This file was auto-generated with a random PSK and a new ML-DSA-65 key\n\
                  # pair. Review and modify every setting below before starting the service.\n\
                  #\n";

    let body = CONFIG_TEMPLATE
        .replace(PSK_PLACEHOLDER, psk_hex)
        .replace("\"./keys/node.key\"", &format!("\"{priv_str}\""))
        .replace("\"./keys/node.pub\"", &format!("\"{pub_str}\""))
        .replace("\"./logs\"", &format!("\"{log_str}\""));

    format!("{header}{body}")
}

// ── Private key permission hardening ─────────────────────────────────────────

/// Restrict permissions on the private key file.
///
/// - Unix: `chmod 0600` (owner read/write only).
/// - Windows: no-op (relies on directory ACL inheritance; explicit ACL
///   hardening is not yet implemented).
pub fn set_private_key_permissions(path: &Path) -> std::io::Result<()> {
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        std::fs::set_permissions(path, std::fs::Permissions::from_mode(0o600))?;
    }
    #[cfg(not(unix))]
    {
        let _ = path;
    }
    Ok(())
}
